on: "0027--09-Sep-2022"
copyright: "2022"
author: "Andrew Jeremy"
title: "OS222: Operating Systems 2022-2"
githublink: "https://github.com/freej1ng/os222/"
myloglink: "/TXT/mylog.txt"
encoding: UTF-8
markdown: kramdown
input: GFM
hard_wrap: false
github: [metadata]
